version: '3'
services:
  postgres:
    container_name: postgres-wallet
    image: postgres:14.3-alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 1024M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata/wallet
    volumes:
      - ./wallet-init.sh:/docker-entrypoint-initdb.d/wallet-init.sh
      - /Users/solvia/application/postgre/wallet:/var/lib/postgresql/data
    ports:
      - 5435:5432