version: '3'
services:
  postgres:
    container_name: postgres-e-wallet
    image: postgres:14.3-alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 1024M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/e-wallet
    volumes:
      - e-wallet:/var/lib/postgresql/data
    ports:
      - 5435:5432
volumes:
  e-wallet: